CREATE TABLE PERSON (ID BIGINT NOT NULL, PERSONNO INTEGER NOT NULL, PERSONTYPE VARCHAR(1) NOT NULL, FIRSTNAME VARCHAR(255), LASTNAME VARCHAR(255), LEGALFORM VARCHAR(15), NAME VARCHAR(255));
ALTER TABLE PERSON ADD CONSTRAINT PERSONPK PRIMARY KEY (ID);
CREATE TABLE ADDRESS (ADDRESSTYPE VARCHAR(10), STREET VARCHAR(255), ZIPCODE INTEGER, CITY VARCHAR(255), PERSONID BIGINT);
ALTER TABLE ADDRESS ADD CONSTRAINT ADDRESSPERSONID FOREIGN KEY (PERSONID) REFERENCES PERSON (ID);