INSERT INTO "PERSON" ("ID", "PERSONNO", "PERSONTYPE", "FIRSTNAME", "LASTNAME", "LEGALFORM", "NAME") VALUES(2000, 200, 'N', 'Bill', 'Gates', NULL, NULL);
INSERT INTO "PERSON" ("ID", "PERSONNO", "PERSONTYPE", "FIRSTNAME", "LASTNAME", "LEGALFORM", "NAME") VALUES(3000, 300, 'N', 'Ken', 'Olsen', NULL, NULL);
INSERT INTO "PERSON" ("ID", "PERSONNO", "PERSONTYPE", "FIRSTNAME", "LASTNAME", "LEGALFORM", "NAME") VALUES(4000, 400, 'L', NULL, NULL, 'AG', 'Microsoft');
INSERT INTO "PERSON" ("ID", "PERSONNO", "PERSONTYPE", "FIRSTNAME", "LASTNAME", "LEGALFORM", "NAME") VALUES(5000, 500, 'L', NULL, NULL, 'AG', 'Google');
INSERT INTO "ADDRESS" ("ADDRESSTYPE", "STREET", "ZIPCODE", "CITY", "PERSONID") VALUES('Hauptsitz', '500 Fifth Avenue North', 98102, 'Seattle', 2000);
INSERT INTO "ADDRESS" ("ADDRESSTYPE", "STREET", "ZIPCODE", "CITY", "PERSONID") VALUES('Ostküste', 'P.O. Box 6176', 20044, 'Washington', 2000);